#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _HCN1_reg(void);
extern void _IC_reg(void);
extern void _IKsin_reg(void);
extern void _MyExp2SynBB_reg(void);
extern void _MyExp2SynNMDABB_reg(void);
extern void _Nca_reg(void);
extern void _ar_traub_reg(void);
extern void _cadad_reg(void);
extern void _cadyn_reg(void);
extern void _cagk_reg(void);
extern void _cal_mh_reg(void);
extern void _cal_mig_reg(void);
extern void _can_mig_reg(void);
extern void _cancr_reg(void);
extern void _canin_reg(void);
extern void _cat_mig_reg(void);
extern void _cat_traub_reg(void);
extern void _catcb_reg(void);
extern void _ch_CavL_reg(void);
extern void _ch_CavN_reg(void);
extern void _ch_KCaS_reg(void);
extern void _ch_Kdrfastngf_reg(void);
extern void _ch_KvAngf_reg(void);
extern void _ch_KvCaB_reg(void);
extern void _ch_Navngf_reg(void);
extern void _ch_leak_reg(void);
extern void _dipole_reg(void);
extern void _dipole_pp_reg(void);
extern void _gabab_reg(void);
extern void _h_BS_reg(void);
extern void _h_harnett_reg(void);
extern void _h_kole_reg(void);
extern void _h_migliore_reg(void);
extern void _hin_reg(void);
extern void _ican_sidi_reg(void);
extern void _iccr_reg(void);
extern void _iconc_Ca_reg(void);
extern void _ikscr_reg(void);
extern void _kBK_reg(void);
extern void _kap_BS_reg(void);
extern void _kapcb_reg(void);
extern void _kapin_reg(void);
extern void _kca_reg(void);
extern void _kctin_reg(void);
extern void _kdmc_BS_reg(void);
extern void _kdr_BS_reg(void);
extern void _kdrcr_reg(void);
extern void _kdrin_reg(void);
extern void _km_reg(void);
extern void _kv_reg(void);
extern void _my_exp2syn_reg(void);
extern void _nafcr_reg(void);
extern void _nafx_reg(void);
extern void _nap_sidi_reg(void);
extern void _nax_BS_reg(void);
extern void _naz_reg(void);
extern void _savedist_reg(void);
extern void _vecstim_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," HCN1.mod");
    fprintf(stderr," IC.mod");
    fprintf(stderr," IKsin.mod");
    fprintf(stderr," MyExp2SynBB.mod");
    fprintf(stderr," MyExp2SynNMDABB.mod");
    fprintf(stderr," Nca.mod");
    fprintf(stderr," ar_traub.mod");
    fprintf(stderr," cadad.mod");
    fprintf(stderr," cadyn.mod");
    fprintf(stderr," cagk.mod");
    fprintf(stderr," cal_mh.mod");
    fprintf(stderr," cal_mig.mod");
    fprintf(stderr," can_mig.mod");
    fprintf(stderr," cancr.mod");
    fprintf(stderr," canin.mod");
    fprintf(stderr," cat_mig.mod");
    fprintf(stderr," cat_traub.mod");
    fprintf(stderr," catcb.mod");
    fprintf(stderr," ch_CavL.mod");
    fprintf(stderr," ch_CavN.mod");
    fprintf(stderr," ch_KCaS.mod");
    fprintf(stderr," ch_Kdrfastngf.mod");
    fprintf(stderr," ch_KvAngf.mod");
    fprintf(stderr," ch_KvCaB.mod");
    fprintf(stderr," ch_Navngf.mod");
    fprintf(stderr," ch_leak.mod");
    fprintf(stderr," dipole.mod");
    fprintf(stderr," dipole_pp.mod");
    fprintf(stderr," gabab.mod");
    fprintf(stderr," h_BS.mod");
    fprintf(stderr," h_harnett.mod");
    fprintf(stderr," h_kole.mod");
    fprintf(stderr," h_migliore.mod");
    fprintf(stderr," hin.mod");
    fprintf(stderr," ican_sidi.mod");
    fprintf(stderr," iccr.mod");
    fprintf(stderr," iconc_Ca.mod");
    fprintf(stderr," ikscr.mod");
    fprintf(stderr," kBK.mod");
    fprintf(stderr," kap_BS.mod");
    fprintf(stderr," kapcb.mod");
    fprintf(stderr," kapin.mod");
    fprintf(stderr," kca.mod");
    fprintf(stderr," kctin.mod");
    fprintf(stderr," kdmc_BS.mod");
    fprintf(stderr," kdr_BS.mod");
    fprintf(stderr," kdrcr.mod");
    fprintf(stderr," kdrin.mod");
    fprintf(stderr," km.mod");
    fprintf(stderr," kv.mod");
    fprintf(stderr," my_exp2syn.mod");
    fprintf(stderr," nafcr.mod");
    fprintf(stderr," nafx.mod");
    fprintf(stderr," nap_sidi.mod");
    fprintf(stderr," nax_BS.mod");
    fprintf(stderr," naz.mod");
    fprintf(stderr," savedist.mod");
    fprintf(stderr," vecstim.mod");
    fprintf(stderr, "\n");
  }
  _HCN1_reg();
  _IC_reg();
  _IKsin_reg();
  _MyExp2SynBB_reg();
  _MyExp2SynNMDABB_reg();
  _Nca_reg();
  _ar_traub_reg();
  _cadad_reg();
  _cadyn_reg();
  _cagk_reg();
  _cal_mh_reg();
  _cal_mig_reg();
  _can_mig_reg();
  _cancr_reg();
  _canin_reg();
  _cat_mig_reg();
  _cat_traub_reg();
  _catcb_reg();
  _ch_CavL_reg();
  _ch_CavN_reg();
  _ch_KCaS_reg();
  _ch_Kdrfastngf_reg();
  _ch_KvAngf_reg();
  _ch_KvCaB_reg();
  _ch_Navngf_reg();
  _ch_leak_reg();
  _dipole_reg();
  _dipole_pp_reg();
  _gabab_reg();
  _h_BS_reg();
  _h_harnett_reg();
  _h_kole_reg();
  _h_migliore_reg();
  _hin_reg();
  _ican_sidi_reg();
  _iccr_reg();
  _iconc_Ca_reg();
  _ikscr_reg();
  _kBK_reg();
  _kap_BS_reg();
  _kapcb_reg();
  _kapin_reg();
  _kca_reg();
  _kctin_reg();
  _kdmc_BS_reg();
  _kdr_BS_reg();
  _kdrcr_reg();
  _kdrin_reg();
  _km_reg();
  _kv_reg();
  _my_exp2syn_reg();
  _nafcr_reg();
  _nafx_reg();
  _nap_sidi_reg();
  _nax_BS_reg();
  _naz_reg();
  _savedist_reg();
  _vecstim_reg();
}
