#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/usr/local/arch/nrn_py3"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/usr/local/arch/nrn_py3/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/u/salvadord/Documents/ISB/Models/m1_paper2019_py3/sim/mod/x86_64/.libs/libnrnmech.so" "$@"
